name: Add Issue Comment

on:
  issues:
     types:
       - labeled

jobs:
  comment-issue:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - run: gh issue comment "$NUMBER" --body "$BODY"
        env:
           GH_TOKEN: ${{secrets.GITHUB_TOKEN}}
           GH_REPO: ${{github.repository}}
           NUMBER: ${{github.event.issue.number}}
           BODY: >
             Please refer guidelines for reference
             :sparkles: Thanks you for your contribution :sparkles:
