name: new workflow for adding label

on:
  issues:
    types:
      - opened

jobs:
  add-label:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - run: gh issue "$NUMBER" --add-label "$LABELS"
        env:
          GH_TOKEN: ${{secrets.GITHUB_TOKEN}}
          GH_REPOSITORY: ${{github.repository}}
          NUMBER: ${{github.event.issue.number}}
          LABELS: bug
    
